const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:4000/api';
const KEY='mtp2026_auth';
function b64(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
export async function beginLogin(){const state=b64(crypto.getRandomValues(new Uint8Array(24)));const verifier=b64(crypto.getRandomValues(new Uint8Array(32)));const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));const challenge=b64(digest);sessionStorage.setItem('mtp_sso_state',state);sessionStorage.setItem('mtp_sso_verifier',verifier);const cfg=await fetch(`${API}/config`).then(r=>r.json());const redirect=cfg.sso.redirect_uri||`${location.origin}/auth/callback`;const u=new URL(`${cfg.sso.issuer}/api/sso/authorize`);u.search=new URLSearchParams({client_id:cfg.sso.client_id||'',redirect_uri:redirect,response_type:'code',scope:'openid profile email',state,code_challenge:challenge,code_challenge_method:'S256'}).toString();location.assign(u.toString())}
export async function finishLogin(){const p=new URLSearchParams(location.search);const state=p.get('state'),code=p.get('code');if(!code||state!==sessionStorage.getItem('mtp_sso_state'))throw Error('INVALID_SSO_STATE');const verifier=sessionStorage.getItem('mtp_sso_verifier');const redirect=`${location.origin}/auth/callback`;const r=await fetch(`${API}/auth/callback`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,state,code_verifier:verifier,redirect_uri:redirect})});const d=await r.json();if(!r.ok)throw Error(d.error||'SSO_LOGIN_FAILED');localStorage.setItem(KEY,JSON.stringify(d));sessionStorage.removeItem('mtp_sso_state');sessionStorage.removeItem('mtp_sso_verifier');history.replaceState({},'',location.pathname);return d}
export function auth(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
export function token(){return auth()?.access_token||''}
export function logout(){localStorage.removeItem(KEY);location.reload()}
export async function api(path,options={}){const headers={...(options.headers||{}),Authorization:`Bearer ${token()}`};return fetch(`${API}${path}`,{...options,headers})}
