import './mtp2026AndroidOS.css';
import { finishVexaLogin, startVexaLogin } from './auth/vexaAuth.js';
const ID='mtp2026-android-os', KEY='mtp2026-default-system-os', PREF='mtp2026-android-prefs';
const APPS=[{id:'store',name:'VexaStore',icon:'▦',color:'#188b7a',url:'https://www.vexastore.2bd.net/'},{id:'account',name:'VexaAccount',icon:'◉',color:'#5277df',url:'https://vexaaccount-management.onrender.com'},{id:'browser',name:'Browser',icon:'◎',color:'#3986ee',url:'https://www.google.com/'},{id:'chat',name:'VexaChat',icon:'▰',color:'#239f83',url:'https://vexachat-ofgc.onrender.com'},{id:'files',name:'Files',icon:'▤',color:'#e6a23c'},{id:'settings',name:'Settings',icon:'⚙',color:'#657386'},{id:'photos',name:'Photos',icon:'✿',color:'#d96a8b'},{id:'camera',name:'Camera',icon:'◉',color:'#7a68cf',native:true},{id:'messages',name:'Messages',icon:'▰',color:'#239f83',url:'https://vexachat-ofgc.onrender.com'}];
const defaults={wifi:true,bluetooth:false,doNotDisturb:false,batterySaver:false,dark:false,brightness:80};
let prefs=readPrefs(),page='home',shade=false,query='',files=[],notifications=[],authSession=null;
function readPrefs(){try{return {...defaults,...JSON.parse(localStorage.getItem(PREF)||'{}')}}catch{return {...defaults}}}
function savePrefs(){try{localStorage.setItem(PREF,JSON.stringify(prefs))}catch{}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function enabled(){return String(document.documentElement.dataset.mtpDeviceMode||localStorage.getItem(KEY)||'android').toLowerCase()==='android'}
function root(){let n=document.getElementById(ID);if(!n){n=document.createElement('div');n.id=ID;document.body.appendChild(n)}return n}
function icon(a,small=false){const inner=a.iconUrl?'<img src="'+esc(a.iconUrl)+'" alt="" loading="lazy"/>':esc(a.icon||'◈');return '<span class="ma-icon'+(small?' small':'')+'" style="--c:'+esc(a.color||'#188b7a')+'">'+inner+'</span>'}
function appButtons(items){return items.map(a=>'<button class="ma-app" data-app="'+esc(a.id)+'">'+icon(a)+'<span>'+esc(a.name)+'</span></button>').join('')}
function installedApps(){const apps=window.MTP2026UniversalOS?.getInstalledApps?.()||[];return apps.filter(a=>a&&a.url&&!APPS.some(s=>s.url===a.url)).map(a=>({id:'installed:'+String(a.id||a.slug||a.url),name:a.title||a.name||'WebApp',icon:'◈',color:'#188b7a',iconUrl:a.userIconUrl||a.iconUrl||null,url:a.url,installedApp:a}));}
function allApps(){return [...APPS,...installedApps()]}
function shadeMarkup(){return '<div class="ma-shade"><div class="ma-handle"></div><header><div><small>QUICK SETTINGS</small><h2>'+new Date().toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'})+'</h2></div><button data-action="settings">⚙</button></header><div class="ma-tiles">'+[['wifi','ᯤ','Internet'],['bluetooth','ᛒ','Bluetooth'],['doNotDisturb','☾','Do Not Disturb'],['batterySaver','♧','Battery Saver']].map(([k,i,l])=>'<button class="ma-tile '+(prefs[k]?'active':'')+'" data-toggle="'+k+'"><b>'+i+'　'+l+'</b><small>'+(prefs[k]?'On':'Off')+'</small></button>').join('')+'</div><label class="ma-bright">☼ <input type="range" min="10" max="100" value="'+prefs.brightness+'" data-brightness/> ☀ <b>'+prefs.brightness+'%</b></label><div class="ma-nhead"><b>Notifications</b><button data-action="clear">Clear all</button></div>'+(notifications.length?notifications.map(n=>'<article class="ma-notice"><b>'+esc(n.title)+'</b><p>'+esc(n.message)+'</p><small>'+n.time+'</small></article>').join(''):'<p class="ma-empty">You’re all caught up. Notifications will appear here.</p>')+'<button class="ma-done" data-action="shade">Done</button></div>'}
function renderHome(){let n=root();n.className='ma-root'+(prefs.dark?' dark':'');let time=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});n.innerHTML='<main class="ma-home"><div class="ma-status"><button data-action="shade">'+time+' · MTP2026</button><button data-action="shade">▮▮▮ ᯤ ▰</button></div><header class="ma-hero"><small>MTP2026 ANDROID OS</small><h1>Good day.</h1><p>Your space, your apps, your settings.</p></header><button class="ma-search" data-action="drawer">⌕　 Search apps and content <span>⌕</span></button><div class="ma-widgets"><button data-action="shade"><small>LOCAL TIME</small><strong>'+time+'</strong><span>Quick settings & notifications</span></button><button data-app="files"><small>YOUR DEVICE</small><strong>Storage</strong><span>Browse selected files</span></button></div><section class="ma-appgrid">'+appButtons([...APPS.filter(a=>['store','browser','chat','files','photos'].includes(a.id)),...installedApps()])+'</section><nav class="ma-dock">'+['store','browser','files','settings'].map(id=>{let a=APPS.find(x=>x.id===id);return '<button data-app="'+id+'">'+icon(a,true)+'</button>'}).join('')+'<button data-action="drawer"><span class="ma-all">⠿</span></button></nav><div class="ma-gesture"><button data-action="home" aria-label="Home"></button></div></main>'+(shade?shadeMarkup():'');bind(n)}
function renderDrawer(){let n=root();n.className='ma-root'+(prefs.dark?' dark':'');let filtered=allApps().filter(a=>(a.name+' '+a.id).toLowerCase().includes(query.toLowerCase()));n.innerHTML='<main class="ma-page"><header class="ma-pagehead"><button data-action="home">‹</button><div><small>APPLICATIONS</small><h1>All apps</h1></div><button data-action="shade">☷</button></header><label class="ma-search">⌕ <input data-query value="'+esc(query)+'" placeholder="Search apps"/></label><section class="ma-appgrid">'+appButtons(filtered)+'</section><div class="ma-gesture"><button data-action="home"></button></div></main>'+(shade?shadeMarkup():'');bind(n);let input=n.querySelector('[data-query]');input?.addEventListener('input',e=>{query=e.target.value;let pos=input.selectionStart;renderDrawer();let next=root().querySelector('[data-query]');next?.focus();next?.setSelectionRange(pos,pos)})}
function renderSettings(){let n=root();n.className='ma-root'+(prefs.dark?' dark':'');n.innerHTML='<main class="ma-page"><header class="ma-pagehead"><button data-action="home">‹</button><div><small>SYSTEM</small><h1>Settings</h1></div><span>⚙</span></header><div class="ma-account"><span>◉</span><div><b>VexaAccount</b><small>'+esc(authSession?.profile?.email||(authSession?.profile?'Signed in':'Sign in to manage identity'))+'</small></div><button data-app="account">›</button></div><section class="ma-group"><h3>Network & connectivity</h3>'+[['wifi','Internet','Wi-Fi preference'],['bluetooth','Connected devices','Bluetooth preference'],['doNotDisturb','Notifications','Quiet mode']].map(([k,t,d])=>'<button class="ma-row" data-toggle="'+k+'"><i>'+({'wifi':'ᯤ','bluetooth':'ᛒ','doNotDisturb':'☾'}[k])+'</i><span><b>'+t+'</b><small>'+d+'</small></span><strong>'+(prefs[k]?'On':'Off')+'</strong></button>').join('')+'</section><section class="ma-group"><h3>Display & personalization</h3><label class="ma-row"><i>☼</i><span><b>Brightness</b><small>Shell display preference</small></span><input type="range" min="10" max="100" value="'+prefs.brightness+'" data-brightness/></label><button class="ma-row" data-toggle="dark"><i>◐</i><span><b>Dark theme</b><small>Change shell appearance</small></span><strong>'+(prefs.dark?'On':'Off')+'</strong></button></section><section class="ma-group"><h3>Device</h3><button class="ma-row" data-app="files"><i>▤</i><span><b>Storage & files</b><small>Browse user-selected files</small></span><strong>›</strong></button><button class="ma-row" data-action="about"><i>ⓘ</i><span><b>About MTP2026</b><small>Version and runtime capabilities</small></span><strong>›</strong></button></section><p class="ma-disclaimer">Network switches here are saved UI preferences, not direct control of host radios. Native device controls require OS permissions.</p></main>';bind(n)}
function renderFiles(){let n=root();n.className='ma-root'+(prefs.dark?' dark':'');n.innerHTML='<main class="ma-page"><header class="ma-pagehead"><button data-action="home">‹</button><div><small>DEVICE</small><h1>Files</h1></div><button class="ma-import" data-action="import">＋ Import</button></header><div class="ma-filehero"><b>Browse your files</b><p>Select files using the device picker. Access remains limited to your selection.</p></div><section class="ma-group"><h3>Recent selections</h3>'+(files.length?files.map(f=>'<div class="ma-file"><span>▧</span><div><b>'+esc(f.name)+'</b><small>'+esc(f.size)+'</small></div></div>').join(''):'<p class="ma-empty">No files selected yet. Tap Import to choose files.</p>')+'</section><p class="ma-disclaimer">Browser mode cannot read unrestricted Android storage or raw system partitions.</p></main>';bind(n)}
function renderAbout(){let n=root();n.className='ma-root'+(prefs.dark?' dark':'');n.innerHTML='<main class="ma-page"><header class="ma-pagehead"><button data-action="settings">‹</button><div><small>SYSTEM</small><h1>About MTP2026</h1></div></header><div class="ma-mark">M</div><h2 class="ma-about-title">MTP2026 Android OS</h2><p class="ma-about-sub">Android-style MTP2026 application shell</p><section class="ma-group"><div class="ma-info"><b>Edition</b><span>Android OS</span></div><div class="ma-info"><b>Runtime</b><span>Web shell + native bridge when available</span></div><div class="ma-info"><b>Guest kernel</b><span>Not running in browser mode</span></div></section><p class="ma-disclaimer">A full Android system requires a bootable image and compatible native or virtualized runtime.</p></main>';bind(n)}
function bind(n){n.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>launch(b.dataset.app));n.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{let k=b.dataset.toggle;prefs[k]=!prefs[k];savePrefs();render()});n.querySelectorAll('[data-brightness]').forEach(b=>b.oninput=()=>{prefs.brightness=+b.value;savePrefs();let x=n.querySelector('.ma-bright b');if(x)x.textContent=prefs.brightness+'%'});n.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{let a=b.dataset.action;if(a==='shade'){shade=!shade;render()}else if(a==='drawer'){page='drawer';renderDrawer()}else if(a==='home'){page='home';shade=false;renderHome()}else if(a==='settings'){page='settings';shade=false;renderSettings()}else if(a==='clear'){notifications=[];render()}else if(a==='import')importFiles();else if(a==='about'){page='about';renderAbout()}})}
function launch(id){let a=allApps().find(x=>x.id===id);if(!a)return;if(a.installedApp){const runtime=window.MTP2026UniversalOS;if(runtime?.openApp){void runtime.openApp(a.installedApp).catch(error=>{notifications.unshift({title:'Could not open '+a.name,message:String(error?.message||error),time:'Now'});shade=true;render()});}else{notifications.unshift({title:'Application runtime unavailable',message:'Reload this MTP2026 Android OS page and try again.',time:'Now'});shade=true;render()}return}if(id==='account'&&!authSession?.profile){startVexaLogin({prompt:'select_account'});return}if(id==='settings'){page='settings';shade=false;renderSettings()}else if(id==='files'){page='files';shade=false;renderFiles()}else if(id==='photos')importFiles('image/*');else if(id==='camera')importFiles('image/*',true);else if(a.native){notifications.unshift({title:a.name,message:'This feature requires a native Android service or device permission.',time:'Now'});shade=true;render()}else if(a.url){if(id==='chat'||id==='messages'){const runtime=window.MTP2026UniversalOS;if(runtime?.openApp){void runtime.openApp(a).catch(()=>{if(window.MTP2026NativePlatform?.nativeOpenExternal)window.MTP2026NativePlatform.nativeOpenExternal(a.url);else window.open(a.url,'_blank','noopener,noreferrer')});return}}try{if(window.MTP2026NativePlatform?.nativeOpenExternal)window.MTP2026NativePlatform.nativeOpenExternal(a.url);else window.open(a.url,'_blank','noopener,noreferrer')}catch{window.open(a.url,'_blank','noopener,noreferrer')}}}
function importFiles(accept='*/*',capture=false){let i=document.createElement('input');i.type='file';i.multiple=!capture;i.accept=accept;if(capture)i.setAttribute('capture','environment');i.onchange=()=>{files=Array.from(i.files||[]).map(f=>({name:f.name,size:f.size<1024?f.size+' B':(f.size/1024).toFixed(1)+' KB'}));notifications.unshift({title:'Files selected',message:files.length+' file(s) selected for this session.',time:'Now'});page='files';renderFiles()};i.click()}
function render(){if(!enabled()){document.getElementById(ID)?.remove();let r=document.getElementById('root');if(r)r.style.display='';return}let r=document.getElementById('root');if(r)r.style.display='none';if(page==='drawer')renderDrawer();else if(page==='settings')renderSettings();else if(page==='files')renderFiles();else if(page==='about')renderAbout();else renderHome()}
function sync(){if(enabled()){if(!document.getElementById(ID))render()}else{document.getElementById(ID)?.remove();let r=document.getElementById('root');if(r)r.style.display=''}}
window.addEventListener('mtp2026:vexastore-library-synced',()=>{if(page==='home')renderHome();else if(page==='drawer')renderDrawer()});window.addEventListener('mtp2026:vexastore-installed',()=>{if(page==='home')renderHome();else if(page==='drawer')renderDrawer()});window.addEventListener('mtp2026:vexastore-uninstalled',()=>{if(page==='home')renderHome();else if(page==='drawer')renderDrawer()});
void finishVexaLogin().then(session=>{authSession=session?.profile?session:null;if(page==='settings')renderSettings();else if(page==='home')renderHome()}).catch(()=>{authSession=null;if(page==='settings')renderSettings()});
window.addEventListener('mtp2026:default-system-os',sync);window.addEventListener('storage',e=>{if(e.key===KEY)sync()});window.addEventListener('load',()=>setTimeout(sync,100));new MutationObserver(sync).observe(document.documentElement,{attributes:true,attributeFilter:['data-mtp-device-mode','data-mtpdevicemode']});sync();
