import './mtp2026GamingOS.css';
const ID='mtp2026-gaming-os',KEY='mtp2026-default-system-os';
let tab='home',controller=null,perf={fps:0},frame=0,last=0,count=0,frameToken=0;
const games=[{name:'VexaStore',genre:'Game library & downloads',icon:'▦',kind:'store',color:'#7c5cff'},{name:'Browser Games',genre:'HTML5 games in your browser',icon:'▶',kind:'browser',color:'#00c7b7'},{name:'Controller Test',genre:'Input and button diagnostics',icon:'⌘',kind:'controller',color:'#e3a34f'},{name:'Performance Center',genre:'Host-reported telemetry',icon:'⌁',kind:'performance',color:'#e7689d'}];
function enabled(){return String(document.documentElement.dataset.mtpDeviceMode||localStorage.getItem(KEY)||'gaming').toLowerCase()==='gaming'}
function root(){let n=document.getElementById(ID);if(!n){n=document.createElement('div');n.id=ID;document.body.appendChild(n)}return n}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pads(){return navigator.getGamepads?Array.from(navigator.getGamepads()).filter(Boolean):[]}
function readTelemetry(){const p=navigator.connection||navigator.mozConnection||navigator.webkitConnection;return {cores:navigator.hardwareConcurrency||null,ram:navigator.deviceMemory||null,network:p?.effectiveType||'Not exposed',saveData:p?.saveData===true}}
function startFps(){if(frameToken)return;const tick=t=>{if(last&&t-last>0){count++;if(t-last>=1000){perf.fps=Math.round(count*1000/(t-last));count=0;last=t;const x=document.querySelector('#'+ID+' [data-fps]');if(x)x.textContent=perf.fps+' FPS'} }else last=t;frameToken=requestAnimationFrame(tick)};frameToken=requestAnimationFrame(tick)}
function stopFps(){if(frameToken)cancelAnimationFrame(frameToken);frameToken=0;last=0;count=0}
function openGame(g){if(g.startsWith('app:')){const key=g.slice(4);const apps=window.MTP2026UniversalOS?.getInstalledApps?.()||[];const app=apps.find(x=>String(x.slug||x.id||x.url)===key);if(app&&window.MTP2026UniversalOS?.openApp){window.MTP2026UniversalOS.openApp(app);return}if(app?.url){window.open(app.url,'_blank','noopener,noreferrer');return}}if(g==='store'){window.open('https://www.vexastore.2bd.net/','_blank','noopener,noreferrer');return}if(g==='browser'){window.open('https://www.google.com/search?q=HTML5+browser+games','_blank','noopener,noreferrer');return}tab=g;render()}
function gameCard(g){return '<button class="mg-game" data-game="'+g.kind+'"><span class="mg-game-art" style="--game-color:'+g.color+'">'+g.icon+'</span><span class="mg-game-copy"><b>'+esc(g.name)+'</b><small>'+esc(g.genre)+'</small></span><span class="mg-launch">Open ↗</span></button>'}\nfunction installedCards(){const apps=window.MTP2026UniversalOS?.getInstalledApps?.()||[];return apps.filter(a=>a&&a.url).map(a=>'<button class="mg-game" data-game="app:'+esc(String(a.slug||a.id||a.url))+'"><span class="mg-game-art" style="--game-color:#188b7a">'+esc(String(a.title||a.name||'A').slice(0,1).toUpperCase())+'</span><span class="mg-game-copy"><b>'+esc(a.title||a.name||'VexaApp')+'</b><small>Installed from VexaStore · '+esc(a.version||'Web app')+'</small></span><span class="mg-launch">Launch ↗</span></button>').join('')}
function renderHome(){let n=root();n.className='mg-root';n.innerHTML='<div class="mg-shell"><header class="mg-top"><div class="mg-brand"><span class="mg-mark">M</span><span><b>MTP2026</b><small>GAMING OS</small></span></div><nav><button class="active" data-tab="home">Home</button><button data-tab="library">Library</button><button data-tab="controller">Controller</button><button data-tab="performance">Performance</button></nav><button class="mg-fullscreen" data-action="fullscreen">⛶ Fullscreen</button></header><section class="mg-hero"><div class="mg-hero-copy"><small>PLAY WITHOUT LIMITS</small><h1>Your next session<br/><em>starts here.</em></h1><p>Game library, controller diagnostics, and live host telemetry in one focused gaming dashboard.</p><button class="mg-primary" data-tab="library">Explore library <span>→</span></button></div><div class="mg-orb"><div class="mg-orb-ring"></div><div class="mg-orb-core">M<span>26</span></div><small>GAMING MODE</small></div></section><section class="mg-section-head"><div><small>YOUR SPACE</small><h2>Quick launch</h2></div><button data-tab="library">View library →</button></section><section class="mg-game-grid">'+games.map(gameCard).join('')+'</section><section class="mg-metrics"><div><small>CONTROLLERS</small><b data-pad-count>'+pads().length+'</b><span>Connected gamepads</span></div><div><small>LIVE RENDER</small><b data-fps>Measuring…</b><span>Browser animation frame rate</span></div><div><small>CPU THREADS</small><b>'+((navigator.hardwareConcurrency||'—'))+'</b><span>Host-reported logical cores</span></div></section><footer class="mg-footer">MTP2026 Gaming OS <span>Independent frontend · Host-dependent capabilities</span></footer></div>';bind(n);startFps();updatePads()}
function renderLibrary(){let n=root();n.className='mg-root';n.innerHTML='<div class="mg-shell"><header class="mg-subhead"><button data-action="home">‹ Home</button><div><small>MTP2026 GAMING OS</small><h1>Game Library</h1></div><button class="mg-fullscreen" data-action="fullscreen">⛶ Fullscreen</button></header><p class="mg-lead">Launch available services and discover browser-playable games. Native PC/console titles require a compatible installed runtime.</p><section class="mg-game-grid">'+games.map(gameCard).join('')+'</section><div class="mg-note">VexaStore opens as an external service. This browser shell does not pretend to install native Windows or console executables.</div></div>';bind(n)}
function renderController(){let n=root(),list=pads();n.className='mg-root';n.innerHTML='<div class="mg-shell"><header class="mg-subhead"><button data-action="home">‹ Home</button><div><small>INPUT LAB</small><h1>Controller Center</h1></div><button data-action="refresh">↻ Refresh</button></header><p class="mg-lead">Connect a gamepad to the device, then press any button. The browser exposes controller state after user interaction on some platforms.</p><section class="mg-controller-card"><div class="mg-controller-icon">⌘</div><div><small>DETECTED DEVICES</small><h2>'+list.length+' controller'+(list.length===1?'':'s')+' connected</h2><p>'+(list.length?'Select a controller below to inspect live input.':'No controller is currently visible to this browser.')+'</p></div></section>'+list.map(p=>'<section class="mg-pad"><b>'+esc(p.id||'Gamepad')+'</b><small>Index '+p.index+' · '+esc(p.mapping||'standard mapping')+'</small><div class="mg-button-grid">'+p.buttons.map((b,i)=>'<div class="mg-button-state '+(b.pressed?'pressed':'')+'"><b>'+i+'</b><small>'+Math.round((b.value||0)*100)+'%</small></div>').join('')+'</div><h3>Axes</h3><div class="mg-axis-grid">'+p.axes.map((a,i)=>'<div><span>Axis '+i+'</span><b>'+Number(a).toFixed(2)+'</b><div class="mg-axis"><i style="width:'+Math.round((Number(a)+1)*50)+'%"></i></div></div>').join('')+'</div></section>').join('')+'<div class="mg-note">Controller access depends on browser support and device permissions. No controller input is fabricated when hardware is absent.</div></div>';bind(n)}
function renderPerformance(){let n=root(),t=readTelemetry();n.className='mg-root';n.innerHTML='<div class="mg-shell"><header class="mg-subhead"><button data-action="home">‹ Home</button><div><small>LIVE TELEMETRY</small><h1>Performance Center</h1></div><button data-action="refresh">↻ Refresh</button></header><p class="mg-lead">Only values exposed by your host browser are shown. These are not GPU benchmarks or temperatures.</p><section class="mg-metric-grid"><article><small>RENDER RATE</small><b data-fps>'+perf.fps+' FPS</b><span>Measured animation callback rate</span></article><article><small>LOGICAL CPU CORES</small><b>'+ (t.cores??'Not exposed')+'</b><span>navigator.hardwareConcurrency</span></article><article><small>MEMORY ESTIMATE</small><b>'+(t.ram?t.ram+' GB':'Not exposed')+'</b><span>Browser deviceMemory hint</span></article><article><small>NETWORK</small><b>'+esc(t.network)+'</b><span>'+(t.saveData?'Data saver is enabled':'Effective connection type')+'</span></article><article><small>GAMEPADS</small><b>'+pads().length+'</b><span>Visible to Gamepad API</span></article><article><small>FULLSCREEN</small><b>'+(document.fullscreenElement?'Active':'Available')+'</b><span>Browser permission dependent</span></article></section><div class="mg-note">GPU utilization, fan speed, CPU temperature and native frame times are not exposed by standard browser APIs. A privileged native service is required for those metrics.</div></div>';bind(n);startFps()}
function updatePads(){const x=document.querySelector('#'+ID+' [data-pad-count]');if(x)x.textContent=pads().length}
function bind(n){n.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});n.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game));n.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{if(b.dataset.action==='home'){tab='home';render()}else if(b.dataset.action==='refresh'){render()}else if(b.dataset.action==='sync-store'){try{await window.MTP2026UniversalOS?.syncApps?.()}catch{}render()}else if(b.dataset.action==='fullscreen'){try{if(!document.fullscreenElement)await root().requestFullscreen();else await document.exitFullscreen()}catch{}}})}
function render(){if(!enabled()){document.getElementById(ID)?.remove();let r=document.getElementById('root');if(r)r.style.display='';stopFps();return}let r=document.getElementById('root');if(r)r.style.display='none';if(tab==='library')renderLibrary();else if(tab==='controller')renderController();else if(tab==='performance')renderPerformance();else renderHome()}
function sync(){if(enabled()){if(!document.getElementById(ID))render()}else{document.getElementById(ID)?.remove();let r=document.getElementById('root');if(r)r.style.display='';stopFps()}}
window.addEventListener('mtp2026:default-system-os',sync);window.addEventListener('storage',e=>{if(e.key===KEY)sync()});window.addEventListener('gamepadconnected',()=>{updatePads();if(tab==='controller')renderController()});window.addEventListener('gamepaddisconnected',()=>{updatePads();if(tab==='controller')renderController()});window.addEventListener('mtp2026:vexastore-library-synced',()=>{if(tab==='library')renderLibrary()});window.addEventListener('mtp2026:vexastore-installed',()=>{if(tab==='library')renderLibrary()});window.addEventListener('mtp2026:vexastore-uninstalled',()=>{if(tab==='library')renderLibrary()});window.addEventListener('load',()=>setTimeout(sync,100));new MutationObserver(sync).observe(document.documentElement,{attributes:true,attributeFilter:['data-mtp-device-mode','data-mtpdevicemode']});sync();
